# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '3.0.2.dev31+g2a097aa.d20230104'
__version_tuple__ = version_tuple = (3, 0, 2, 'dev31', 'g2a097aa.d20230104')
