#! /usr/bin/env python
"""
Output LST and Julian date at the provided location.
"""

import aipy, sys, optparse, ephem

p = optparse.OptionParser()
p.set_usage('lst [options]')
p.set_description(__doc__)
p.add_option('-j', '--juldate', dest='juldate', type='float', 
    default=ephem.julian_date(), help='Use provided julian date.')
p.add_option('-l', '--loc', dest='loc', default='pwa303',
    help='Use location-specific info for this location (default pwa303).')
opts, args = p.parse_args(sys.argv[1:])

aa = aipy.loc.get_loc(opts.loc)
aa.set_jultime(opts.juldate)
print 'LST:', aa.sidereal_time(),
print '     Julian Date:', opts.juldate,
print '     Day:', aa.date

